### ISSUE TITLE
Add .gitattributes for Solidity syntax highlighting on GitHub

### ISSUE THREAD

**Issue by veox** [ledgerwatch/eth_state#2]
An example can be found in the OpenZeppelin repo:

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/.gitattributes

**Comment by AlexeyAkhunov** [comment]
Thank you, I have done it now, maybe I need to wait for GitHub to realise

**Comment by AlexeyAkhunov** [comment]
Works now, thank you so much!
